export const actionTypes = {
    GET_CUSTOMER_LIST_INPUT: "GET_CUSTOMER_LIST_INPUT",
    GET_CUSTOMER_LIST: "GET_CUSTOMER_LIST",
    GET_PROMOTION_ORDER_LIST_INPUT:"GET_PROMOTION_ORDER_LIST_INPUT",
    GET_PRODUCT_ORDER_LIST: "GET_PRODUCT_ORDER_LIST",
    GET_PROMOTION_PRODUCT_INPUT: "GET_PROMOTION_PRODUCT_INPUT",
    GET_PRODUCT_PROMOTION_LIST: "GET_PRODUCT_PROMOTION_LIST",
    GET_PRODUCT_SOLD_LIST_INPUT:"GET_PRODUCT_SOLD_LIST_INPUT",
    GET_PRODUCT_SOLD_LIST: "GET_PRODUCT_SOLD_LIST",
    GET_REFUNDED_LIST_INPUT:"GET_REFUNDED_LIST_INPUT",
    GET_REFUNDED_LIST: "GET_REFUNDED_LIST",
}