const customers = {
    GET_CUSTOMER_LIST_INPUT: "GET_CUSTOMER_LIST_INPUT",
    GET_CUSTOMER_LIST_SUCCESS: "GET_CUSTOMER_LIST_SUCCESS",
    GET_CUSTOMER_LIST_FAILURE: "GET_CUSTOMER_LIST_FAILURE",
    GET_CUSTOMER_LIST_REQUEST: "GET_CUSTOMER_LIST_REQUEST",
}
const productOrder = {
    GET_PRODUCT_ORDER_LIST_INPUT: "GET_PRODUCT_ORDER_LIST_INPUT",
    GET_PRODUCT_ORDER_LIST_SUCCESS: "GET_PRODUCT_ORDER_LIST_SUCCESS",
    GET_PRODUCT_ORDER_LIST_REQUEST: "GET_PRODUCT_ORDER_LIST_REQUEST",
    GET_PRODUCT_ORDER_LIST_FAILURE: "GET_PRODUCT_ORDER_LIST_FAILURE",
}
const promotionProduct = {
    GET_PROMOTION_PRODUCT_INPUT: "GET_PROMOTION_PRODUCT_INPUT",
    GET_PRODUCT_PROMOTION_LIST_SUCCESS: "GET_PRODUCT_PROMOTION_LIST_SUCCESS",
    GET_PRODUCT_PROMOTION_LIST_FAILURE: "GET_PRODUCT_PROMOTION_LIST_FAILURE",
    GET_PRODUCT_PROMOTION_LIST_REQUEST: "GET_PRODUCT_PROMOTION_LIST_REQUEST",
}
const productSold = {
    GET_PRODUCT_SOLD_LIST_INPUT: "GET_PRODUCT_SOLD_LIST_INPUT",
    GET_PRODUCT_SOLD_LIST_SUCCESS: "GET_PRODUCT_SOLD_LIST_SUCCESS",
    GET_PRODUCT_SOLD_LIST_FAILURE: "GET_PRODUCT_SOLD_LIST_FAILURE",
    GET_PRODUCT_SOLD_LIST_REQUEST: "GET_PRODUCT_SOLD_LIST_REQUEST",
}
const refunded = {
    GET_REFUNDED_LIST_INPUT: "GET_REFUNDED_LIST_INPUT",
    GET_REFUNDED_LIST_SUCCESS: "GET_REFUNDED_LIST_SUCCESS",
    GET_REFUNDED_LIST_REQUEST: "GET_REFUNDED_LIST_REQUEST",
    GET_REFUNDED_LIST_FAILURE: "GET_REFUNDED_LIST_FAILURE",
}

export const actionTypes = {
    ...customers,
    ...productOrder,
    ...promotionProduct,
    ...productSold,
    ...refunded
}