export const actionTypes = {
    GET_ALL_ORDER_LISTINGS: "GET_ALL_ORDER_LISTINGS",
    GET_ORDER_LISTING_INPUT : "GET_ORDER_LISTING_INPUT",
    GET_ORDER_LISTING_DETAILS: "GET_ORDER_LISTING_DETAILS",
    UPDATE_ORDER_LISTING_DETAILS: "UPDATE_ORDER_LISTING_DETAILS"
}