const orderListing = {
    GET_ALL_ORDER_LISTING_REQUEST: 'GET_ALL_ORDER_LISTING_REQUEST',
    GET_ALL_ORDER_LISTING_FAILURE: 'GET_ALL_ORDER_LISTING_FAILURE',
    GET_ALL_ORDER_LISTING_SUCCESS: "GET_ALL_ORDER_LISTING_SUCCESS",
}

const orderListingDetail = {
    GET_ORDER_LISTING_DETAILS_SUCCESS: "GET_ORDER_LISTING_DETAILS_SUCCESS",
    GET_ORDER_LISTING_DETAILS_FAILURE: "GET_ORDER_LISTING_DETAILS_FAILURE",
    GET_ORDER_LISTING_DETAILS_REQUEST: "GET_ORDER_LISTING_DETAILS_REQUEST",
}

const updateOrderListing = {
    UPDATE_ORDER_LISTING_DETAILS_SUCCESS: "UPDATE_ORDER_LISTING_DETAILS_SUCCESS",
    UPDATE_ORDER_LISTING_DETAILS_REQUEST: "UPDATE_ORDER_LISTING_DETAILS_REQUEST",
    UPDATE_ORDER_LISTING_DETAILS_FAILURE: "UPDATE_ORDER_LISTING_DETAILS_FAILURE"
}
export const actionTypes = {
    ...orderListing,
    ...orderListingDetail,
    ...updateOrderListing
}